{% set name = "carbonplan" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/carbonplan-{{ version }}.tar.gz
  sha256: 7bff6303727941e30654fa5d6491c439a05db076ee6dc0ed0ed020cee0309d32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools >=30.3.0
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - watermark

test:
  imports:
    - carbonplan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/carbonplan-python
  summary: CarbonPlan namespace package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell
    - maxrjones
    - norlandrhagen
