{% set name = "cmip6-downscaling" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmip6_downscaling-{{ version }}.tar.gz
  sha256: 212ebac77645544b366f53b3921682b487cb64648090ef500bcfdecc6c408b0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.9
    - adlfs >=2022.2.0
    - carbonplan-data
    - carbonplan
    - cf_xarray >=0.7.3
    - cmip6_preprocessing
    - dask-core
    - dask-kubernetes
    - donfig >=0.7.0
    - fsspec
    - intake <=0.7.0
    - intake-esm >=2022.9.18
    - intake-xarray
    - ndpyramid ==0.0.6
    - pandas
    - prefect ==0.15.13
    - rechunker
    - regionmask
    - scikit-downscale >=0.1.2
    - scikit-learn
    - scipy
    - universal_pathlib >=0.0.12
    - xarray >=2022.3.0
    - xarray-datatree ==0.0.6
    - xarray-schema >=0.0.3
    - xclim
    - xesmf
    - zarr >=2.11.3

test:
  imports:
    - cmip6_downscaling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/cmip6-downscaling
  summary: climate downscaling using cmip6 data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell
    - maxrjones
    - norlandrhagen
