{% set name = "carbonplan-data" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/carbonplan-data-{{ version }}.tar.gz
  sha256: 8f1fea3701d099b25741f7828c27f2b3bfbbaf7e0abfdd5cbb0030c058303dbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - setuptools >=30.3.0
    - pip
  run:
    - python >=3.7
    - carbonplan
    - urlpath
    - wget

test:
  imports:
    - carbonplan_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/data
  summary: Preprocessing utilities for CarbonPlan's data catalog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell
    - maxrjones
    - norlandrhagen
